import { Incident, Volunteer, DigitizationItem, VerificationItem } from '@/types'

export const mockIncidents: Incident[] = [
  {
    id: '1',
    title: 'Flooding in Downtown District',
    category: 'Flood',
    location: 'Downtown District, Central City',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    severity: 8,
    impact: 9,
    urgencyScore: 76,
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'active',
    reporterName: 'John Smith',
    description: 'Multiple streets flooded with water levels rising. Several buildings affected.',
    affectedCount: 247,
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '2',
    title: 'Earthquake Damage - Market District',
    category: 'Earthquake',
    location: 'Market District, Eastern Zone',
    coordinates: { lat: 40.7589, lng: -73.9851 },
    severity: 7,
    impact: 8,
    urgencyScore: 59,
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'active',
    reporterName: 'Maria Garcia',
    description: 'Significant structural damage to buildings. Several injuries reported.',
    affectedCount: 185,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '3',
    title: 'Medical Supply Shortage',
    category: 'Medical',
    location: 'Central Hospital, Healthcare Hub',
    coordinates: { lat: 40.7580, lng: -73.9855 },
    severity: 6,
    impact: 7,
    urgencyScore: 43,
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Dr. Ahmed Hassan',
    description: 'Critical shortage of antibiotics and pain medication.',
    affectedCount: 450,
    photoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop',
    verified: false,
    geminiVerified: false,
  },
  {
    id: '4',
    title: 'Landslide Alert - Mountain Road',
    category: 'Landslide',
    location: 'Mountain Road, Northern Region',
    coordinates: { lat: 40.8134, lng: -73.9740 },
    severity: 8,
    impact: 7,
    urgencyScore: 59,
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    status: 'active',
    reporterName: 'Robert Winters',
    description: 'Major landslide blocking main mountain route. Multiple vehicles trapped.',
    affectedCount: 32,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: false,
  },
  {
    id: '5',
    title: 'Fire Outbreak - Industrial Zone',
    category: 'Fire',
    location: 'Industrial Zone, West District',
    coordinates: { lat: 40.7069, lng: -73.9831 },
    severity: 9,
    impact: 8,
    urgencyScore: 76,
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    status: 'active',
    reporterName: 'Carlos Rodriguez',
    description: 'Large industrial fire spreading. Evacuations in progress.',
    affectedCount: 1200,
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
]

export const mockVolunteers: Volunteer[] = [
  {
    id: '1',
    name: 'Alice Thompson',
    skills: ['Medical', 'First Aid', 'CPR'],
    distance: 0.8,
    reliabilityScore: 0.96,
    status: 'active',
    avatarInitials: 'AT',
    email: 'alice.thompson@example.com',
    contact: '+1-555-0101',
    certifications: ['EMT', 'Certified Nurse'],
    pastDeployments: 24,
  },
  {
    id: '2',
    name: 'David Chen',
    skills: ['Search & Rescue', 'Navigation', 'Equipment Operation'],
    distance: 1.2,
    reliabilityScore: 0.94,
    status: 'active',
    avatarInitials: 'DC',
    email: 'david.chen@example.com',
    contact: '+1-555-0102',
    certifications: ['SAR Certified', 'Rope Rescue'],
    pastDeployments: 18,
  },
  {
    id: '3',
    name: 'Emma Watson',
    skills: ['Communication', 'Coordination', 'Logistics'],
    distance: 0.5,
    reliabilityScore: 0.98,
    status: 'active',
    avatarInitials: 'EW',
    email: 'emma.watson@example.com',
    contact: '+1-555-0103',
    certifications: ['Project Management'],
    pastDeployments: 31,
  },
  {
    id: '4',
    name: 'Frank Miller',
    skills: ['Engineering', 'Infrastructure', 'Heavy Equipment'],
    distance: 2.1,
    reliabilityScore: 0.89,
    status: 'inactive',
    avatarInitials: 'FM',
    email: 'frank.miller@example.com',
    contact: '+1-555-0104',
    certifications: ['Structural Engineer'],
    pastDeployments: 12,
  },
  {
    id: '5',
    name: 'Grace Lee',
    skills: ['Counseling', 'Mental Health Support', 'Care Coordination'],
    distance: 0.3,
    reliabilityScore: 0.97,
    status: 'active',
    avatarInitials: 'GL',
    email: 'grace.lee@example.com',
    contact: '+1-555-0105',
    certifications: ['Licensed Counselor', 'Trauma Specialist'],
    pastDeployments: 22,
  },
  {
    id: '6',
    name: 'Hassan Ibrahim',
    skills: ['Translation', 'Community Outreach', 'Cultural Liaison'],
    distance: 1.5,
    reliabilityScore: 0.92,
    status: 'active',
    avatarInitials: 'HI',
    email: 'hassan.ibrahim@example.com',
    contact: '+1-555-0106',
    certifications: ['Interpreter', 'Community Health Worker'],
    pastDeployments: 19,
  },
  {
    id: '7',
    name: 'Isabella Martinez',
    skills: ['Medical', 'Surgery', 'Trauma Care'],
    distance: 0.7,
    reliabilityScore: 0.99,
    status: 'deployed',
    avatarInitials: 'IM',
    email: 'isabella.martinez@example.com',
    contact: '+1-555-0107',
    certifications: ['Surgeon', 'Trauma Specialist'],
    pastDeployments: 28,
  },
  {
    id: '8',
    name: 'James Wilson',
    skills: ['Water Safety', 'Rescue Operations', 'Swimming'],
    distance: 1.8,
    reliabilityScore: 0.91,
    status: 'active',
    avatarInitials: 'JW',
    email: 'james.wilson@example.com',
    contact: '+1-555-0108',
    certifications: ['Lifeguard', 'Water Rescue Diver'],
    pastDeployments: 15,
  },
]

export const mockDigitizationItems: DigitizationItem[] = [
  {
    id: '1',
    filename: 'field_survey_001.pdf',
    pageCount: 3,
    status: 'processed',
    uploadedAt: new Date(Date.now() - 60 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1586075850295-ab3c1cac8a60?w=400&h=500&fit=crop',
    progress: 100,
    source: 'batch',
    extractedData: {
      incidentType: 'Flood',
      location: 'North Ward, River Basin',
      date: '2026-04-15',
      severity: 'High',
      reporterName: 'Sarah Johnson',
      description: 'Heavy rainfall causing street flooding',
      affectedCount: '150',
    },
    verification: {
      reviewedBy: 'Ops Admin',
      reviewedAt: new Date(Date.now() - 45 * 60000),
      notes: 'Confirmed against phone call log.',
    },
  },
  {
    id: '2',
    filename: 'field_survey_002.jpg',
    pageCount: 1,
    status: 'processing',
    uploadedAt: new Date(Date.now() - 30 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1552664730-d307ca884978?w=400&h=500&fit=crop',
    progress: 62,
    source: 'single',
    extractedData: null,
  },
  {
    id: '3',
    filename: 'field_survey_003.png',
    pageCount: 2,
    status: 'failed',
    uploadedAt: new Date(Date.now() - 120 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?w=400&h=500&fit=crop',
    progress: 100,
    source: 'batch',
    extractedData: null,
  },
  {
    id: '4',
    filename: 'evacuation_form_004.pdf',
    pageCount: 4,
    status: 'pending',
    uploadedAt: new Date(Date.now() - 15 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?w=400&h=500&fit=crop',
    progress: 0,
    source: 'batch',
    extractedData: null,
  },
  {
    id: '5',
    filename: 'medical_intake_005.jpg',
    pageCount: 1,
    status: 'processed',
    uploadedAt: new Date(Date.now() - 80 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1584515933487-779824d29309?w=400&h=500&fit=crop',
    progress: 100,
    source: 'single',
    extractedData: {
      incidentType: 'Medical Emergency',
      location: 'Camp Delta, South Block',
      date: '2026-04-20',
      severity: 'Medium',
      reporterName: 'Daniel Ortega',
      description: 'Cluster of dehydration and fever cases in temporary shelter.',
      affectedCount: '23',
    },
  },
  {
    id: '6',
    filename: 'bridge_damage_006.png',
    pageCount: 2,
    status: 'rescanned',
    uploadedAt: new Date(Date.now() - 200 * 60000),
    imageUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=400&h=500&fit=crop',
    progress: 100,
    source: 'batch',
    extractedData: {
      incidentType: 'Infrastructure Damage',
      location: 'West Bridge Crossing',
      date: '2026-04-20',
      severity: 'High',
      reporterName: 'Lina Park',
      description: 'Initial scan was blurry; rescan confirms major deck crack.',
      affectedCount: '450',
    },
    verification: {
      reviewedBy: 'Field Lead',
      reviewedAt: new Date(Date.now() - 90 * 60000),
      notes: 'Rescan required due to poor lighting.',
    },
  },
]

export const mockVerificationItems: VerificationItem[] = [
  {
    id: '1',
    reporterName: 'Thomas Green',
    incidentType: 'Earthquake',
    timestamp: new Date(Date.now() - 45 * 60000),
    location: 'East Downtown, Block 7',
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
    reportText: 'Significant ground shaking felt at 14:32. Multiple buildings showing cracks.',
    aiAnalysis: 'Photo contains structural damage consistent with seismic activity. Confidence: 87%.',
    reportedLocation: { lat: 40.7589, lng: -73.9851 },
    submissionLocation: { lat: 40.7585, lng: -73.9850 },
    communityConfirmations: 12,
    status: 'pending',
  },
  {
    id: '2',
    reporterName: 'Sofia Hernandez',
    incidentType: 'Fire',
    timestamp: new Date(Date.now() - 20 * 60000),
    location: 'Industrial Complex, Section C',
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=400&fit=crop',
    reportText: 'Active fire visible from residential area. Heavy smoke visible.',
    aiAnalysis: 'Image shows active fire with significant smoke plume. Industrial materials identifiable. Confidence: 94%.',
    reportedLocation: { lat: 40.7069, lng: -73.9831 },
    submissionLocation: { lat: 40.7070, lng: -73.9832 },
    communityConfirmations: 28,
    status: 'pending',
  },
  {
    id: '3',
    reporterName: 'Marcus Thompson',
    incidentType: 'Flood',
    timestamp: new Date(Date.now() - 90 * 60000),
    location: 'River Road, Riverside District',
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=400&fit=crop',
    reportText: 'Water levels rising rapidly. Multiple vehicles stranded.',
    aiAnalysis: 'Photo shows urban flooding with vehicles partially submerged. Water depth estimated 0.5-1m. Confidence: 91%.',
    reportedLocation: { lat: 40.7128, lng: -74.0060 },
    submissionLocation: { lat: 40.7125, lng: -74.0065 },
    communityConfirmations: 18,
    status: 'verified',
  },
]

export const CREDENTIAL_CATEGORIES = [
  'Medical',
  'Search & Rescue',
  'Engineering',
  'Counseling',
  'Translation',
  'Communication',
  'Logistics',
  'Navigation',
]

export const INCIDENT_CATEGORIES = [
  'Flood',
  'Earthquake',
  'Fire',
  'Landslide',
  'Medical Emergency',
  'Transportation Accident',
  'Infrastructure Damage',
  'Food Shortage',
  'Water Shortage',
]

export const URGENCY_LEVELS = [
  { value: 'critical', label: 'Critical', color: 'red' },
  { value: 'high', label: 'High', color: 'orange' },
  { value: 'medium', label: 'Medium', color: 'yellow' },
  { value: 'low', label: 'Low', color: 'blue' },
]

export const DEFAULT_AI_WEIGHTS = {
  skillMatch: 0.4,
  proximity: 0.3,
  availability: 0.2,
  reliability: 0.1,
}

export const DEFAULT_URGENCY_MULTIPLIERS = {
  impact: 1.2,
  severity: 1.3,
}

const incidentCategories = ['Flood', 'Earthquake', 'Fire', 'Landslide', 'Medical Emergency', 'Infrastructure Damage']
const volunteerSkillSets = [
  ['Medical', 'First Aid'],
  ['Search & Rescue', 'Navigation'],
  ['Logistics', 'Coordination'],
  ['Engineering', 'Infrastructure'],
  ['Counseling', 'Community Outreach'],
]

while (mockIncidents.length < 20) {
  const idx = mockIncidents.length + 1
  mockIncidents.push({
    id: String(idx),
    title: `Incident Report ${idx}`,
    category: incidentCategories[idx % incidentCategories.length],
    location: `Zone ${idx}, Coordination Sector`,
    coordinates: { lat: 40.7 + idx * 0.002, lng: -74 + idx * 0.002 },
    severity: 4 + (idx % 6),
    impact: 3 + (idx % 7),
    urgencyScore: 35 + (idx % 60),
    timestamp: new Date(Date.now() - idx * 600000).toISOString(),
    status: idx % 3 === 0 ? 'pending' : idx % 5 === 0 ? 'resolved' : 'active',
    reporterName: `Reporter ${idx}`,
    description: `Field update for incident ${idx}.`,
    affectedCount: 30 + idx * 7,
    verified: idx % 2 === 0,
    geminiVerified: idx % 3 === 0,
  })
}

while (mockVolunteers.length < 30) {
  const idx = mockVolunteers.length + 1
  const skills = volunteerSkillSets[idx % volunteerSkillSets.length]
  mockVolunteers.push({
    id: String(idx),
    name: `Volunteer ${idx}`,
    skills,
    distance: Number((0.5 + (idx % 9) * 0.3).toFixed(1)),
    reliabilityScore: Number((0.8 + (idx % 18) * 0.01).toFixed(2)),
    status: idx % 4 === 0 ? 'deployed' : idx % 6 === 0 ? 'inactive' : 'active',
    avatarInitials: `V${idx}`,
    email: `volunteer${idx}@example.com`,
    contact: `+1-555-${String(1000 + idx).slice(-4)}`,
    certifications: [`${skills[0]} Certified`],
    pastDeployments: 6 + idx,
  })
}

while (mockVerificationItems.length < 10) {
  const idx = mockVerificationItems.length + 1
  mockVerificationItems.push({
    id: String(idx),
    reporterName: `Citizen ${idx}`,
    incidentType: incidentCategories[idx % incidentCategories.length],
    timestamp: new Date(Date.now() - idx * 420000),
    location: `Community Block ${idx}`,
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=400&fit=crop',
    reportText: `Community report ${idx} submitted from mobile portal.`,
    aiAnalysis: 'Photo contains evidence consistent with reported category. Confidence: 88%.',
    reportedLocation: { lat: 40.7 + idx * 0.002, lng: -74 + idx * 0.002 },
    submissionLocation: { lat: 40.7005 + idx * 0.002, lng: -73.9995 + idx * 0.002 },
    communityConfirmations: 2 + idx,
    status: idx % 4 === 0 ? 'verified' : 'pending',
  })
}
