import { Incident, Volunteer, Assignment, GlobalConfig } from '../types/index.js'

export const mockIncidents: Incident[] = [
  {
    id: '1',
    title: 'Flooding in Downtown District',
    category: 'Flood',
    location: 'Downtown District, Central City',
    coordinates: { lat: 40.7128, lng: -74.0060 },
    severity: 8,
    urgencyScore: 76,
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'John Smith',
    description: 'Multiple streets flooded with water levels rising. Several buildings affected.',
    affectedCount: 247,
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '2',
    title: 'Earthquake Damage - Market District',
    category: 'Earthquake',
    location: 'Market District, Eastern Zone',
    coordinates: { lat: 40.7589, lng: -73.9851 },
    severity: 7,
    urgencyScore: 59,
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Maria Garcia',
    description: 'Significant structural damage to buildings. Several injuries reported.',
    affectedCount: 185,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '3',
    title: 'Medical Supply Shortage',
    category: 'Medical Emergency',
    location: 'Central Hospital, Healthcare Hub',
    coordinates: { lat: 40.7580, lng: -73.9855 },
    severity: 6,
    urgencyScore: 43,
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Dr. Ahmed Hassan',
    description: 'Critical shortage of antibiotics and pain medication.',
    affectedCount: 450,
    photoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop',
    verified: false,
    geminiVerified: false,
  },
  {
    id: '4',
    title: 'Landslide Alert - Mountain Road',
    category: 'Landslide',
    location: 'Mountain Road, Northern Region',
    coordinates: { lat: 40.8134, lng: -73.9740 },
    severity: 8,
    urgencyScore: 59,
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Robert Winters',
    description: 'Major landslide blocking main mountain route. Multiple vehicles trapped.',
    affectedCount: 32,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: false,
  },
  {
    id: '5',
    title: 'Fire Outbreak - Industrial Zone',
    category: 'Fire',
    location: 'Industrial Zone, West District',
    coordinates: { lat: 40.7069, lng: -73.9831 },
    severity: 9,
    urgencyScore: 76,
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Carlos Rodriguez',
    description: 'Large industrial fire spreading. Evacuations in progress.',
    affectedCount: 1200,
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
]

while (mockIncidents.length < 20) {
  const idx = mockIncidents.length + 1
  mockIncidents.push({
    id: String(idx),
    title: `Incident Report ${idx}`,
    category: ['Flood', 'Earthquake', 'Fire', 'Landslide', 'Medical Emergency', 'Infrastructure Damage'][idx % 6],
    location: `Zone ${idx}, Coordination Sector`,
    coordinates: { lat: 40.7 + idx * 0.002, lng: -74 + idx * 0.002 },
    severity: 4 + (idx % 6),
    urgencyScore: 35 + (idx % 60),
    timestamp: new Date(Date.now() - idx * 600000).toISOString(),
    status: idx % 3 === 0 ? 'pending' : idx % 5 === 0 ? 'resolved' : 'pending',
    reporterName: `Reporter ${idx}`,
    description: `Field update for incident ${idx}.`,
    affectedCount: 30 + idx * 7,
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=300&fit=crop',
    verified: idx % 2 === 0,
    geminiVerified: idx % 3 === 0,
  })
}

export const mockVolunteers: Volunteer[] = [
  {
    id: '1',
    name: 'Alice Thompson',
    email: 'alice.thompson@example.com',
    skills: ['Medical', 'First Aid', 'CPR'],
    status: 'active',
    currentCoordinates: { lat: 40.713, lng: -74.006 },
    reliabilityScore: 0.96,
    fcmToken: 'token-alice',
    certifications: ['EMT', 'Certified Nurse'],
    pastDeployments: 24,
  },
  {
    id: '2',
    name: 'David Chen',
    email: 'david.chen@example.com',
    skills: ['Search & Rescue', 'Navigation', 'Equipment Operation'],
    status: 'active',
    currentCoordinates: { lat: 40.759, lng: -73.985 },
    reliabilityScore: 0.94,
    fcmToken: 'token-david',
    certifications: ['SAR Certified', 'Rope Rescue'],
    pastDeployments: 18,
  },
  {
    id: '3',
    name: 'Emma Watson',
    email: 'emma.watson@example.com',
    skills: ['Communication', 'Coordination', 'Logistics'],
    status: 'active',
    currentCoordinates: { lat: 40.758, lng: -73.986 },
    reliabilityScore: 0.98,
    fcmToken: 'token-emma',
    certifications: ['Project Management'],
    pastDeployments: 31,
  },
  {
    id: '4',
    name: 'Frank Miller',
    email: 'frank.miller@example.com',
    skills: ['Engineering', 'Infrastructure', 'Heavy Equipment'],
    status: 'inactive',
    currentCoordinates: { lat: 40.707, lng: -73.983 },
    reliabilityScore: 0.89,
    fcmToken: 'token-frank',
    certifications: ['Structural Engineer'],
    pastDeployments: 12,
  },
  {
    id: '5',
    name: 'Grace Lee',
    email: 'grace.lee@example.com',
    skills: ['Counseling', 'Mental Health Support', 'Care Coordination'],
    status: 'active',
    currentCoordinates: { lat: 40.713, lng: -74.005 },
    reliabilityScore: 0.97,
    fcmToken: 'token-grace',
    certifications: ['Licensed Counselor', 'Trauma Specialist'],
    pastDeployments: 22,
  },
  {
    id: '6',
    name: 'Hassan Ibrahim',
    email: 'hassan.ibrahim@example.com',
    skills: ['Translation', 'Community Outreach', 'Cultural Liaison'],
    status: 'active',
    currentCoordinates: { lat: 40.712, lng: -74.007 },
    reliabilityScore: 0.92,
    fcmToken: 'token-hassan',
    certifications: ['Interpreter', 'Community Health Worker'],
    pastDeployments: 19,
  },
  {
    id: '7',
    name: 'Isabella Martinez',
    email: 'isabella.martinez@example.com',
    skills: ['Medical', 'Surgery', 'Trauma Care'],
    status: 'deployed',
    currentCoordinates: { lat: 40.759, lng: -73.984 },
    reliabilityScore: 0.99,
    fcmToken: 'token-isabella',
    certifications: ['Surgeon', 'Trauma Specialist'],
    pastDeployments: 28,
  },
  {
    id: '8',
    name: 'James Wilson',
    email: 'james.wilson@example.com',
    skills: ['Water Safety', 'Rescue Operations', 'Swimming'],
    status: 'active',
    currentCoordinates: { lat: 40.706, lng: -73.984 },
    reliabilityScore: 0.91,
    fcmToken: 'token-james',
    certifications: ['Lifeguard', 'Water Rescue Diver'],
    pastDeployments: 15,
  },
]

while (mockVolunteers.length < 30) {
  const idx = mockVolunteers.length + 1
  const skills = [
    ['Medical', 'First Aid'],
    ['Search & Rescue', 'Navigation'],
    ['Logistics', 'Coordination'],
    ['Engineering', 'Infrastructure'],
    ['Counseling', 'Community Outreach'],
  ][idx % 5]
  mockVolunteers.push({
    id: String(idx),
    name: `Volunteer ${idx}`,
    email: `volunteer${idx}@example.com`,
    skills,
    status: idx % 4 === 0 ? 'deployed' : idx % 6 === 0 ? 'inactive' : 'active',
    currentCoordinates: { lat: 40.7 + idx * 0.002, lng: -74 + idx * 0.002 },
    reliabilityScore: Number((0.8 + (idx % 18) * 0.01).toFixed(2)),
    fcmToken: `token-${idx}`,
    certifications: [`${skills[0]} Certified`],
    pastDeployments: 6 + idx,
  })
}

export const mockAssignments: Assignment[] = [
  {
    id: 'a1',
    incidentId: '1',
    volunteerId: '7',
    status: 'dispatched',
    startTime: new Date(Date.now() - 10 * 60000).toISOString(),
  },
]

export const mockGlobalConfig: GlobalConfig = {
  a: 0.4,
  b: 0.3,
  c: 0.2,
  d: 0.1,
  useVertexAI: false,
  endpointId: '',
}

export const mockDigitizationQueue: any[] = [
  {
    id: '1',
    filename: 'field_survey_001.pdf',
    status: 'processed',
    uploadedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    progress: 100,
    source: 'batch',
    extractedData: {
      incidentType: 'Flood',
      location: 'North Ward, River Basin',
      date: '2026-04-15',
      severity: 'High',
      reporterName: 'Sarah Johnson',
      description: 'Heavy rainfall causing street flooding',
      affectedCount: '150',
    },
  },
  {
    id: '2',
    filename: 'field_survey_002.jpg',
    status: 'processing',
    uploadedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    progress: 62,
    source: 'single',
    extractedData: null,
  },
]

export const mockVerifications: any[] = [
  {
    id: '1',
    reporterName: 'Thomas Green',
    incidentType: 'Earthquake',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    location: 'East Downtown, Block 7',
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
    reportText: 'Significant ground shaking felt at 14:32. Multiple buildings showing cracks.',
    aiAnalysis: 'Photo contains structural damage consistent with seismic activity. Confidence: 87%.',
    reportedLocation: { lat: 40.7589, lng: -73.9851 },
    submissionLocation: { lat: 40.7585, lng: -73.9850 },
    communityConfirmations: 12,
    status: 'pending',
  },
  {
    id: '2',
    reporterName: 'Sofia Hernandez',
    incidentType: 'Fire',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    location: 'Industrial Complex, Section C',
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=400&fit=crop',
    reportText: 'Active fire visible from residential area. Heavy smoke visible.',
    aiAnalysis: 'Image shows active fire with significant smoke plume. Industrial materials identifiable. Confidence: 94%.',
    reportedLocation: { lat: 40.7069, lng: -73.9831 },
    submissionLocation: { lat: 40.7070, lng: -73.9832 },
    communityConfirmations: 28,
    status: 'pending',
  },
]
