import { Incident, Volunteer, Assignment, GlobalConfig } from '../types/index.js'

export const mockIncidents: Incident[] = [
  {
    id: '1',
    title: 'Flooding in Downtown District',
    category: 'Flood',
    location: 'Downtown District, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2514, lng: 81.6296 },
    severity: 8,
    urgencyScore: 76,
    timestamp: new Date(Date.now() - 5 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'John Smith',
    description: 'Multiple streets flooded with water levels rising. Several buildings affected.',
    affectedCount: 247,
    photoUrl: 'https://images.unsplash.com/photo-1547471080-7cc2caa01a7e?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '2',
    title: 'Earthquake Damage - Market District',
    category: 'Earthquake',
    location: 'Market District, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2400, lng: 81.6400 },
    severity: 7,
    urgencyScore: 45,
    timestamp: new Date(Date.now() - 15 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Maria Garcia',
    description: 'Significant structural damage to buildings. Several injuries reported.',
    affectedCount: 185,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '3',
    title: 'Medical Supply Shortage',
    category: 'Medical Emergency',
    location: 'Central Hospital, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2600, lng: 81.6100 },
    severity: 6,
    urgencyScore: 43,
    timestamp: new Date(Date.now() - 30 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Dr. Ahmed Hassan',
    description: 'Critical shortage of antibiotics and pain medication.',
    affectedCount: 450,
    photoUrl: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=400&h=300&fit=crop',
    verified: false,
    geminiVerified: false,
  },
  {
    id: '4',
    title: 'Landslide Alert - Mountain Road',
    category: 'Landslide',
    location: 'Mountain Road, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2700, lng: 81.6500 },
    severity: 6,
    urgencyScore: 48,
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Robert Winters',
    description: 'Minor landslide blocking side road. Slow traffic.',
    affectedCount: 32,
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: false,
  },
  {
    id: '5',
    title: 'Fire Outbreak - Industrial Zone',
    category: 'Fire',
    location: 'Industrial Zone, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2300, lng: 81.6000 },
    severity: 9,
    urgencyScore: 80,
    timestamp: new Date(Date.now() - 2 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Carlos Rodriguez',
    description: 'Large industrial fire spreading. Evacuations in progress.',
    affectedCount: 1200,
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
  {
    id: '6',
    title: 'Power Outage - North Ward',
    category: 'Infrastructure Damage',
    location: 'North Ward, Raipur, Chhattisgarh',
    coordinates: { lat: 21.2800, lng: 81.6200 },
    severity: 5,
    urgencyScore: 40,
    timestamp: new Date(Date.now() - 60 * 60000).toISOString(),
    status: 'pending',
    reporterName: 'Sunil Gupta',
    description: 'Widespread power outage affecting residential areas.',
    affectedCount: 3000,
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=300&fit=crop',
    verified: true,
    geminiVerified: true,
  },
]

export const mockVolunteers: Volunteer[] = [
  {
    id: '1',
    name: 'Alice Thompson',
    email: 'alice.thompson@gmail.com',
    skills: ['Medical', 'First Aid', 'CPR'],
    status: 'active',
    homeCoordinates: { lat: 21.2514, lng: 81.6296 },
    currentCoordinates: { lat: 21.2514, lng: 81.6296 },
    reliabilityScore: 0.96,
    fcmToken: 'token-alice',
    certifications: ['EMT', 'Certified Nurse'],
    pastDeployments: 24,
    avatarInitials: 'AT',
    distance: 2.3,
  },
  {
    id: '2',
    name: 'David Chen',
    email: 'david.chen@gmail.com',
    skills: ['Search & Rescue', 'Navigation', 'Equipment Operation'],
    status: 'active',
    homeCoordinates: { lat: 21.2379, lng: 81.6463 },
    currentCoordinates: { lat: 21.2379, lng: 81.6463 },
    reliabilityScore: 0.94,
    fcmToken: 'token-david',
    certifications: ['SAR Certified', 'Rope Rescue'],
    pastDeployments: 18,
    avatarInitials: 'DC',
    distance: 5.1,
  },
  {
    id: '3',
    name: 'Emma Watson',
    email: 'emma.watson@gmail.com',
    skills: ['Communication', 'Coordination', 'Logistics'],
    status: 'active',
    homeCoordinates: { lat: 21.2787, lng: 81.6113 },
    currentCoordinates: { lat: 21.2787, lng: 81.6113 },
    reliabilityScore: 0.98,
    fcmToken: 'token-emma',
    certifications: ['Project Management'],
    pastDeployments: 31,
    avatarInitials: 'EW',
    distance: 4.8,
  },
  {
    id: '4',
    name: 'Frank Miller',
    email: 'frank.miller@gmail.com',
    skills: ['Engineering', 'Infrastructure', 'Heavy Equipment'],
    status: 'inactive',
    homeCoordinates: { lat: 21.2443, lng: 81.6056 },
    currentCoordinates: { lat: 21.2443, lng: 81.6056 },
    reliabilityScore: 0.89,
    fcmToken: 'token-frank',
    certifications: ['Structural Engineer'],
    pastDeployments: 12,
    avatarInitials: 'FM',
    distance: 1.2,
  },
  {
    id: '5',
    name: 'Grace Lee',
    email: 'grace.lee@gmail.com',
    skills: ['Counseling', 'Mental Health Support', 'Care Coordination'],
    status: 'active',
    homeCoordinates: { lat: 21.2678, lng: 81.6345 },
    currentCoordinates: { lat: 21.2678, lng: 81.6345 },
    reliabilityScore: 0.97,
    fcmToken: 'token-grace',
    certifications: ['Licensed Counselor', 'Trauma Specialist'],
    pastDeployments: 22,
    avatarInitials: 'GL',
    distance: 2.5,
  },
  {
    id: '6',
    name: 'Hassan Ibrahim',
    email: 'hassan.ibrahim@gmail.com',
    skills: ['Translation', 'Community Outreach', 'Cultural Liaison'],
    status: 'active',
    homeCoordinates: { lat: 21.2556, lng: 81.6198 },
    currentCoordinates: { lat: 21.2556, lng: 81.6198 },
    reliabilityScore: 0.92,
    fcmToken: 'token-hassan',
    certifications: ['Interpreter', 'Community Health Worker'],
    pastDeployments: 19,
    avatarInitials: 'HI',
    distance: 2.1,
  },
  {
    id: '7',
    name: 'Isabella Martinez',
    email: 'isabella.martinez@gmail.com',
    skills: ['Medical', 'Surgery', 'Trauma Care'],
    status: 'deployed',
    homeCoordinates: { lat: 21.2890, lng: 81.6234 },
    currentCoordinates: { lat: 21.2890, lng: 81.6234 },
    reliabilityScore: 0.99,
    fcmToken: 'token-isabella',
    certifications: ['Surgeon', 'Trauma Specialist'],
    pastDeployments: 28,
    avatarInitials: 'IM',
    distance: 5.0,
  },
  {
    id: '8',
    name: 'James Wilson',
    email: 'james.wilson@gmail.com',
    skills: ['Water Safety', 'Rescue Operations', 'Swimming'],
    status: 'active',
    homeCoordinates: { lat: 21.2334, lng: 81.6512 },
    currentCoordinates: { lat: 21.2334, lng: 81.6512 },
    reliabilityScore: 0.91,
    fcmToken: 'token-james',
    certifications: ['Lifeguard', 'Water Rescue Diver'],
    pastDeployments: 15,
    avatarInitials: 'JW',
    distance: 1.5,
  },
]

while (mockVolunteers.length < 30) {
  const idx = mockVolunteers.length + 1
  const skills = [
    ['Medical', 'First Aid'],
    ['Search & Rescue', 'Navigation'],
    ['Logistics', 'Coordination'],
    ['Engineering', 'Infrastructure'],
    ['Counseling', 'Community Outreach'],
  ][idx % 5]
  const name = `Volunteer ${idx}`
  const coords = { 
    lat: 21.15 + ((idx * 0.037) % 0.2), 
    lng: 81.55 + ((idx * 0.053) % 0.2) 
  }
  mockVolunteers.push({
    id: String(idx),
    name,
    email: `volunteer${idx}@gmail.com`,
    skills,
    status: idx % 4 === 0 ? 'deployed' : idx % 6 === 0 ? 'inactive' : 'active',
    homeCoordinates: coords,
    currentCoordinates: coords,
    reliabilityScore: Number((0.8 + (idx % 18) * 0.01).toFixed(2)),
    fcmToken: `token-${idx}`,
    certifications: [`${skills[0]} Certified`],
    pastDeployments: 6 + idx,
    avatarInitials: name.split(' ').map(n => n[0]).join(''),
    distance: Number((1 + idx * 0.3).toFixed(1)),
  })
}

export const mockAssignments: Assignment[] = [
  {
    id: 'a1',
    incidentId: '1',
    volunteerId: '7',
    status: 'dispatched',
    startTime: new Date(Date.now() - 10 * 60000).toISOString(),
  },
]

export const mockGlobalConfig: GlobalConfig = {
  a: 0.4,
  b: 0.3,
  c: 0.2,
  d: 0.1,
  useVertexAI: false,
  endpointId: '',
}

export const mockDigitizationQueue: any[] = [
  {
    id: '1',
    filename: 'field_survey_001.pdf',
    status: 'processed',
    uploadedAt: new Date(Date.now() - 60 * 60000).toISOString(),
    progress: 100,
    source: 'batch',
    extractedData: {
      incidentType: 'Flood',
      location: 'North Ward, River Basin',
      date: '2026-04-15',
      severity: 'High',
      reporterName: 'Sarah Johnson',
      description: 'Heavy rainfall causing street flooding',
      affectedCount: '150',
    },
  },
  {
    id: '2',
    filename: 'field_survey_002.jpg',
    status: 'processing',
    uploadedAt: new Date(Date.now() - 30 * 60000).toISOString(),
    progress: 62,
    source: 'single',
    extractedData: null,
  },
]

export const mockVerifications: any[] = [
  {
    id: '1',
    reporterName: 'Thomas Green',
    incidentType: 'Earthquake',
    timestamp: new Date(Date.now() - 45 * 60000).toISOString(),
    location: 'East Downtown, Raipur, Chhattisgarh',
    photoUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop',
    reportText: 'Significant ground shaking felt at 14:32. Multiple buildings showing cracks.',
    aiAnalysis: 'Photo contains structural damage consistent with seismic activity. Confidence: 87%.',
    reportedLocation: { lat: 21.2400, lng: 81.6400 },
    submissionLocation: { lat: 21.2395, lng: 81.6398 },
    communityConfirmations: 12,
    status: 'pending',
  },
  {
    id: '2',
    reporterName: 'Sofia Hernandez',
    incidentType: 'Fire',
    timestamp: new Date(Date.now() - 20 * 60000).toISOString(),
    location: 'Industrial Complex, Raipur, Chhattisgarh',
    photoUrl: 'https://images.unsplash.com/photo-1559027615-cd4628902d4a?w=400&h=400&fit=crop',
    reportText: 'Active fire visible from residential area. Heavy smoke visible.',
    aiAnalysis: 'Image shows active fire with significant smoke plume. Industrial materials identifiable. Confidence: 94%.',
    reportedLocation: { lat: 21.2300, lng: 81.6000 },
    submissionLocation: { lat: 21.2305, lng: 81.6005 },
    communityConfirmations: 28,
    status: 'pending',
  },
]
